insert into public.company_relationship_graph (
  id,
  source_ticker,
  source_name,
  target_ticker,
  target_name,
  relationship_type,
  strength,
  is_directional,
  notes,
  provenance
)
values
  (
    'f1111111-1111-1111-1111-111111111111',
    'NVDA',
    'NVIDIA Corporation',
    'TSM',
    'Taiwan Semiconductor Manufacturing',
    'Supplier',
    0.9200,
    true,
    'TSMC manufactures NVIDIA''s leading-edge AI chips.',
    '{"source_name":"manual_relationship_seed","source_record_id":"nvda-tsm-supplier-v1"}'::jsonb
  ),
  (
    'f1222222-2222-2222-2222-222222222222',
    'NVDA',
    'NVIDIA Corporation',
    'AMD',
    'Advanced Micro Devices',
    'Competitor',
    0.8700,
    false,
    'NVIDIA and AMD compete across GPU and AI accelerator markets.',
    '{"source_name":"manual_relationship_seed","source_record_id":"nvda-amd-competitor-v1"}'::jsonb
  ),
  (
    'f1333333-3333-3333-3333-333333333333',
    'NVDA',
    'NVIDIA Corporation',
    'AVGO',
    'Broadcom',
    'Sector Peer',
    0.6400,
    false,
    'Broadcom is a semiconductor infrastructure peer for NVIDIA.',
    '{"source_name":"manual_relationship_seed","source_record_id":"nvda-avgo-sector-peer-v1"}'::jsonb
  ),
  (
    'f1444444-4444-4444-4444-444444444444',
    'NVDA',
    'NVIDIA Corporation',
    'MSFT',
    'Microsoft Corporation',
    'Customer',
    0.8200,
    true,
    'Microsoft is a major buyer of NVIDIA AI infrastructure.',
    '{"source_name":"manual_relationship_seed","source_record_id":"nvda-msft-customer-v1"}'::jsonb
  ),
  (
    'f1555555-5555-5555-5555-555555555555',
    'NVDA',
    'NVIDIA Corporation',
    'GOOGL',
    'Alphabet Inc.',
    'Customer',
    0.7800,
    true,
    'Alphabet consumes NVIDIA infrastructure for AI workloads.',
    '{"source_name":"manual_relationship_seed","source_record_id":"nvda-googl-customer-v1"}'::jsonb
  ),
  (
    'f1666666-6666-6666-6666-666666666666',
    'NVDA',
    'NVIDIA Corporation',
    'QCOM',
    'Qualcomm Incorporated',
    'Sector Peer',
    0.5800,
    false,
    'Qualcomm is a semiconductor platform peer across edge AI and compute.',
    '{"source_name":"manual_relationship_seed","source_record_id":"nvda-qcom-sector-peer-v1"}'::jsonb
  ),
  (
    'f1777777-7777-7777-7777-777777777777',
    'TSLA',
    'Tesla, Inc.',
    'RIVN',
    'Rivian Automotive',
    'Competitor',
    0.7400,
    false,
    'Rivian is an EV peer and competitive read-through name for Tesla.',
    '{"source_name":"manual_relationship_seed","source_record_id":"tsla-rivn-competitor-v1"}'::jsonb
  ),
  (
    'f1888888-8888-8888-8888-888888888888',
    'TSLA',
    'Tesla, Inc.',
    'PANW',
    'Panasonic Holdings',
    'Supplier',
    0.6300,
    true,
    'Panasonic is treated as a battery supply relationship in the current project data.',
    '{"source_name":"manual_relationship_seed","source_record_id":"tsla-panw-supplier-v1"}'::jsonb
  ),
  (
    'f1999999-9999-9999-9999-999999999999',
    'TSLA',
    'Tesla, Inc.',
    'QCOM',
    'Qualcomm Incorporated',
    'Supply Chain Dependency',
    0.5200,
    true,
    'Qualcomm components are used as a supply-chain dependency proxy for vehicle electronics.',
    '{"source_name":"manual_relationship_seed","source_record_id":"tsla-qcom-supply-chain-v1"}'::jsonb
  ),
  (
    'f1aaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'LLY',
    'Eli Lilly and Company',
    'NVO',
    'Novo Nordisk',
    'Competitor',
    0.8100,
    false,
    'Novo Nordisk is Lilly''s closest GLP-1 competitor.',
    '{"source_name":"manual_relationship_seed","source_record_id":"lly-nvo-competitor-v1"}'::jsonb
  ),
  (
    'f1bbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    'LLY',
    'Eli Lilly and Company',
    'NVO',
    'Novo Nordisk',
    'Regulatory Peer',
    0.7400,
    false,
    'Lilly and Novo share overlapping regulatory pathways in obesity and diabetes.',
    '{"source_name":"manual_relationship_seed","source_record_id":"lly-nvo-regulatory-peer-v1"}'::jsonb
  ),
  (
    'f1cccccc-cccc-cccc-cccc-cccccccccccc',
    'AAPL',
    'Apple Inc.',
    'GOOGL',
    'Alphabet Inc.',
    'Sector Peer',
    0.6900,
    false,
    'Alphabet is a large-cap platform peer for Apple.',
    '{"source_name":"manual_relationship_seed","source_record_id":"aapl-googl-sector-peer-v1"}'::jsonb
  ),
  (
    'f1dddddd-dddd-dddd-dddd-dddddddddddd',
    'AAPL',
    'Apple Inc.',
    'GOOGL',
    'Alphabet Inc.',
    'Regulatory Peer',
    0.7200,
    false,
    'Apple and Alphabet face similar platform regulation and antitrust scrutiny.',
    '{"source_name":"manual_relationship_seed","source_record_id":"aapl-googl-regulatory-peer-v1"}'::jsonb
  ),
  (
    'f1eeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    'AAPL',
    'Apple Inc.',
    'QCOM',
    'Qualcomm Incorporated',
    'Supplier',
    0.5900,
    true,
    'Qualcomm remains a device component supplier proxy for Apple.',
    '{"source_name":"manual_relationship_seed","source_record_id":"aapl-qcom-supplier-v1"}'::jsonb
  ),
  (
    'f1ffffff-ffff-ffff-ffff-ffffffffffff',
    'MSFT',
    'Microsoft Corporation',
    'GOOGL',
    'Alphabet Inc.',
    'Competitor',
    0.7900,
    false,
    'Microsoft and Alphabet compete in cloud and AI infrastructure.',
    '{"source_name":"manual_relationship_seed","source_record_id":"msft-googl-competitor-v1"}'::jsonb
  ),
  (
    'f2111111-1111-1111-1111-111111111111',
    'MSFT',
    'Microsoft Corporation',
    'AMZN',
    'Amazon.com, Inc.',
    'Competitor',
    0.8300,
    false,
    'AWS is Microsoft''s main hyperscale cloud competitor.',
    '{"source_name":"manual_relationship_seed","source_record_id":"msft-amzn-competitor-v1"}'::jsonb
  ),
  (
    'f2222222-2222-2222-2222-222222222222',
    'MSFT',
    'Microsoft Corporation',
    'ORCL',
    'Oracle Corporation',
    'Sector Peer',
    0.6100,
    false,
    'Oracle is a software infrastructure peer relevant to Microsoft capex announcements.',
    '{"source_name":"manual_relationship_seed","source_record_id":"msft-orcl-sector-peer-v1"}'::jsonb
  )
on conflict (id) do update
set
  source_ticker = excluded.source_ticker,
  source_name = excluded.source_name,
  target_ticker = excluded.target_ticker,
  target_name = excluded.target_name,
  relationship_type = excluded.relationship_type,
  strength = excluded.strength,
  is_directional = excluded.is_directional,
  notes = excluded.notes,
  provenance = excluded.provenance,
  updated_at = timezone('utc', now());
